### ISSUE TITLE
推荐一个新的梯子

### ISSUE THREAD

**Issue by XDCODING** [getlantern/wercker-android#6]
蓝灯最近一直连不上，试了试这个还可以，随手分享。
https://antss.orxs.me/aff/Gt5u

**Comment by huxiuqiangwei** [comment]
现在ss节点的太容易封了，体验太差，推荐个自用的V2ray和Trojan协议的梯子，不容易封，还能刷奈飞，客服售后给力 

https://xbsj4621.fun/i/ems072

大家可以试试
